# Generated by Django 2.0.7 on 2018-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180709_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/1.png', upload_to='avatars/'),
        ),
    ]
