# Generated by Django 2.0.7 on 2018-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
