# Generated by Django 2.0.7 on 2018-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
