# Generated by Django 2.0.7 on 2018-07-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
