# Generated by Django 2.0.7 on 2018-07-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.IntegerField(default=True),
        ),
    ]
