# Generated by Django 2.0.7 on 2018-07-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180713_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
